#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Скрипт для автоматического извлечения YouTube cookies из браузера
"""

import os
import sys
import logging

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

def extract_cookies_browser_cookie3():
    """Извлекает cookies из браузера используя browser_cookie3"""
    try:
        import browser_cookie3
        
        logger.info("Попытка извлечения cookies из браузеров...")
        
        # Пробуем разные браузеры
        browsers = {
            'Chrome': browser_cookie3.chrome,
            'Edge': browser_cookie3.edge,
            'Firefox': browser_cookie3.firefox,
            'Chromium': browser_cookie3.chromium,
            'Opera': browser_cookie3.opera,
        }
        
        cookies_found = {}
        
        for browser_name, browser_func in browsers.items():
            try:
                logger.info(f"Проверка {browser_name}...")
                cookies = browser_func(domain_name='youtube.com')
                
                cookie_list = list(cookies)
                if cookie_list:
                    logger.info(f"✅ Найдено {len(cookie_list)} cookies в {browser_name}")
                    cookies_found[browser_name] = cookie_list
                    
            except Exception as e:
                logger.debug(f"  {browser_name}: {e}")
                continue
        
        if not cookies_found:
            logger.warning("❌ Не найдено cookies ни в одном браузере")
            return None
        
        # Выбираем браузер с наибольшим количеством cookies
        best_browser = max(cookies_found.items(), key=lambda x: len(x[1]))
        browser_name, cookies = best_browser
        
        logger.info(f"Используем cookies из {browser_name}")
        
        # Сохраняем в формате Netscape
        output_file = 'youtube_cookies.txt'
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by extract_youtube_cookies.py\n")
            f.write("# Edit at your own risk.\n\n")
            
            for cookie in cookies:
                # Формат Netscape: domain flag path secure expiration name value
                domain = cookie.domain
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.path
                secure = 'TRUE' if cookie.secure else 'FALSE'
                expiration = str(int(cookie.expires)) if cookie.expires else '0'
                name = cookie.name
                value = cookie.value
                
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")
        
        logger.info(f"✅ Cookies сохранены в {output_file}")
        return output_file
        
    except ImportError:
        logger.error("❌ Библиотека browser_cookie3 не установлена")
        return None
    except Exception as e:
        logger.error(f"❌ Ошибка извлечения cookies: {e}")
        return None

def extract_cookies_yt_dlp():
    """Извлекает cookies используя yt-dlp"""
    try:
        import subprocess
        
        logger.info("Попытка извлечения cookies через yt-dlp...")
        
        # Пробуем разные браузеры
        browsers = ['chrome', 'edge', 'firefox', 'chromium', 'opera']
        
        for browser in browsers:
            try:
                logger.info(f"Проверка {browser}...")
                result = subprocess.run(
                    [
                        sys.executable, '-m', 'yt_dlp',
                        '--cookies-from-browser', browser,
                        '--cookies', 'youtube_cookies.txt',
                        '--skip-download',
                        'https://www.youtube.com/'
                    ],
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                
                if result.returncode == 0 and os.path.exists('youtube_cookies.txt'):
                    logger.info(f"✅ Cookies успешно извлечены из {browser}")
                    return 'youtube_cookies.txt'
                    
            except subprocess.TimeoutExpired:
                logger.debug(f"  {browser}: таймаут")
                continue
            except Exception as e:
                logger.debug(f"  {browser}: {e}")
                continue
        
        logger.warning("❌ Не удалось извлечь cookies через yt-dlp")
        return None
        
    except Exception as e:
        logger.error(f"❌ Ошибка yt-dlp: {e}")
        return None

def main():
    logger.info("=" * 60)
    logger.info("YouTube Cookies Extractor")
    logger.info("=" * 60)
    logger.info("")
    
    # Проверяем, вошли ли вы в YouTube в браузере
    logger.info("⚠️  ВАЖНО: Убедитесь, что вы вошли в YouTube в браузере!")
    logger.info("")
    
    # Метод 1: browser_cookie3 (быстрее и надежнее)
    logger.info("Метод 1: Извлечение через browser_cookie3")
    result = extract_cookies_browser_cookie3()
    
    if result:
        logger.info("")
        logger.info("=" * 60)
        logger.info("✅ УСПЕХ! Cookies извлечены и сохранены.")
        logger.info("=" * 60)
        logger.info("Теперь парсер чата должен работать!")
        logger.info("")
        return 0
    
    # Метод 2: yt-dlp (резервный)
    logger.info("")
    logger.info("Метод 2: Извлечение через yt-dlp")
    result = extract_cookies_yt_dlp()
    
    if result:
        logger.info("")
        logger.info("=" * 60)
        logger.info("✅ УСПЕХ! Cookies извлечены и сохранены.")
        logger.info("=" * 60)
        logger.info("Теперь парсер чата должен работать!")
        logger.info("")
        return 0
    
    # Не удалось извлечь
    logger.error("")
    logger.error("=" * 60)
    logger.error("❌ ОШИБКА: Не удалось извлечь cookies")
    logger.error("=" * 60)
    logger.error("")
    logger.error("Возможные причины:")
    logger.error("1. Вы не вошли в YouTube в браузере")
    logger.error("2. Браузер закрыт (закройте все окна браузера и попробуйте снова)")
    logger.error("3. Браузер не поддерживается")
    logger.error("")
    logger.error("Решение:")
    logger.error("1. Откройте Chrome/Edge/Firefox")
    logger.error("2. Войдите на youtube.com")
    logger.error("3. Закройте браузер полностью")
    logger.error("4. Запустите этот скрипт снова")
    logger.error("")
    
    return 1

if __name__ == "__main__":
    try:
        exit_code = main()
        
        # Пауза перед закрытием
        input("\nНажмите Enter для выхода...")
        sys.exit(exit_code)
        
    except KeyboardInterrupt:
        logger.info("\n\nПрервано пользователем")
        sys.exit(1)
    except Exception as e:
        logger.error(f"\n\n❌ Неожиданная ошибка: {e}", exc_info=True)
        input("\nНажмите Enter для выхода...")
        sys.exit(1)

